### ISSUE TITLE
Queries on the missing files of franka_planning and path_planning

### ISSUE THREAD

**Issue by gftww** [scenediffuser/Scene-Diffuser#14]
Thank you for your great job！
I just want to follow these five benchmarks that you provided.
However, both the task of **franka_planning and path_planning have no test files** for evaluating their success rates.
In addition, the visualizer called **FK2PlanVisualizer** seems to have disappeared.
Could you upload these files? Help me follow the convincing evaluation metrics.

Appreciate your responses.
Best wishes
Thank you

**Comment by Silverster98** [comment]
Thanks for your interest in our work.

In franka_planning and path_planning tasks, we evaluate the model using `scripts/{TASK}/plan.sh` instead of `test.sh` files. Please check out these scripts carefully for a comprehensive understanding.

We didn't provide a visualizer for the franka_planning task, as it is already integrated within Isaac Gym. I remember that a visualization window should automatically appear once you execute the `plan.sh` script.

For more details, feel free to ask.

**Comment by gftww** [comment]
Sorry for the late reply.
Thank you very much.
